config/routes.rb
Rails.application.routes.draw do

  resources :words
  resources :results
  resources :subcategories
  resources :categories
  devise_for :users, :controllers => {registrations: 'registrations'}
  root to: 'pages#index'

  get 'pages/contact'

  get 'pages/about'

  get 'pages/subcategory_list'

  get 'pages/word_list'

  get 'pages/word'

  get 'pages/test'

  get 'pages/exam'

  get 'pages/algorithm'

  get 'pages/score'

  get 'pages/my_result'

  get 'set_language/polish'

  get 'set_language/english'

end

app/models/result.rb
class Result < ActiveRecord::Base
  belongs_to :user
  belongs_to :word
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_action :set_result, only: [:show, :edit, :update, :destroy]

  # GET /results
  # GET /results.json
  def index
    @results = Result.all
  end

  # GET /results/1
  # GET /results/1.json
  def show
  end

  # GET /results/new
  def new
    @result = Result.new
  end

  # GET /results/1/edit
  def edit
  end

  # POST /results
  # POST /results.json
  def create
    @result = Result.new(result_params)

    respond_to do |format|
      if @result.save
        format.html {redirect_to @result, notice: 'Result was successfully created.'}
        format.json {render :show, status: :created, location: @result}
      else
        format.html {render :new}
        format.json {render json: @result.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /results/1
  # PATCH/PUT /results/1.json
  def update
    respond_to do |format|
      if @result.update(result_params)
        format.html {redirect_to @result, notice: 'Result was successfully updated.'}
        format.json {render :show, status: :ok, location: @result}
      else
        format.html {render :edit}
        format.json {render json: @result.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /results/1
  # DELETE /results/1.json
  def destroy
    @result.destroy
    respond_to do |format|
      format.html {redirect_to results_url, notice: 'Result was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_result
    @result = Result.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def result_params
    params.require(:result).permit(:result, :user_id, :word_id)
  end
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/results/_form.html.erb
<%= simple_form_for(@result) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :result, label: t('admin.result') %>
    <strong><%= t('admin.user') %></strong>
    <%= f.collection_select :user_id, User.order(:username), :id, :username, {}, {:class => 'form-control'} %><br/>
    <strong><%= t('admin.word') %></strong>
    <%= f.collection_select :word_id, Word.order(:name), :id, :name, {}, {:class => 'form-control'} %><br/>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-success' %>
  </div>
<% end %>

app/views/results/edit.html.erb
<h1><%= t('admin.result') %></h1>

<%= render 'form' %>
<br/>

<%= link_to t('admin.show'), @result, class: 'btn btn-warning' %>
<%= link_to t('admin.back'), results_path, class: 'btn btn-danger' %>

app/views/results/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t('admin.result') %></h1>

<table class="table table-hover">
  <thead>
  <tr>
    <th><%= t('admin.result') %></th>
    <th><%= t('admin.user') %></th>
    <th><%= t('admin.word') %></th>
    <th><%= t('admin.created_at') %></th>
    <th><%= t('admin.updated_at') %></th>
    <th colspan='3' style='width: 15%; text-align: center;'><%= t('admin.action') %></th>
  </tr>
  </thead>

  <tbody>
  <% @results.each do |result| %>
    <tr>
      <td><%= result.result %></td>
      <td><%= User.find(result.user_id).username %></td>
      <td><%= Word.find(result.word_id).name %></td>
      <td><%= result.created_at %></td>
      <td><%= result.updated_at %></td>
      <td><%= link_to t('admin.show'), result, class: 'btn btn-default' %></td>
      <td><%= link_to t('admin.edit'), edit_result_path(result), class: 'btn btn-default' %></td>
      <td><%= link_to t('admin.delete'), result, class: 'btn btn-default', method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to t('admin.new_result'), new_result_path, class: 'btn btn-success' %>

app/views/results/new.html.erb
<h1><%= t('admin.new_result') %></h1>

<%= render 'form' %>
<br/>
<%= link_to t('admin.back'), results_path, class: 'btn btn-danger' %>

app/views/results/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= t('admin.result') %>:</strong>
  <%= @result.result %>
</p>

<p>
  <strong><%= t('admin.user') %>:</strong>
  <%= User.find(@result.user_id).inspect %>
</p>

<p>
  <strong><%= t('admin.word') %>:</strong>
  <%= Word.find(@result.word_id).inspect %>
</p>

<%= link_to t('admin.edit'), edit_result_path(@result), class: 'btn btn-warning' %>
<%= link_to t('admin.back'), results_path, class: 'btn btn-danger' %>