config/routes.rb
Rails.application.routes.draw do

  resources :words
  resources :results
  resources :subcategories
  resources :categories
  devise_for :users, :controllers => {registrations: 'registrations'}
  root to: 'pages#index'

  get 'pages/contact'

  get 'pages/about'

  get 'pages/subcategory_list'

  get 'pages/word_list'

  get 'pages/word'

  get 'pages/test'

  get 'pages/exam'

  get 'pages/algorithm'

  get 'pages/score'

  get 'pages/my_result'

  get 'set_language/polish'

  get 'set_language/english'

end

app/views/pages/about.html.erb
<h1> <%= t('about') %> </h1>
<%= raw t('about_page') %>

app/views/pages/algorithm.html.erb
<div class="center">
  <h1 style="text-align:center;"><%= t('algorithm_fill') %></h1>
  <br/>

  <%= form_for :answer, url: pages_score_path, method: :get do |form| %>
    <% if params[:lang].to_i == 1 %>
      <% i = 0 %>
      <% while i < @words_hash.keys.length do %>
        <%= t('enter') + @words_hash.keys[0 + i] + (params[:lang].to_i == 0 ? t('in_polish') : t('in_english')) + "   :" %>
        <%= form.text_field @words_hash.values[0 + i].strip.to_sym, required: true, size: 40 %><br/>
        <br/>
        <% i += 1 %>
      <% end %>
    <% else %>
      <% i = 0 %>
      <% while i < @words_hash.keys.length do %>
        <%= t('enter') + @words_hash.values[0 + i] + (params[:lang].to_i == 0 ? t('in_polish') : t('in_english')) + "   :" %>
        <%= form.text_field @words_hash.keys[0 + i].strip.to_sym, required: true, size: 40 %><br/>
        <br/>
        <% i += 1 %>
      <% end %>
    <% end %>

    <%= form.hidden_field :id, value: params[:id] %>
    <%= form.hidden_field :alg, value: params[:alg] %>
    <%= form.hidden_field :lang, value: params[:lang] %>
    <%= form.submit value: t('submit') %>
  <% end %>
</div>

app/views/pages/contact.html.erb
<h1><%= t('contact') %></h1>
<h2> Email: Oskar.bir@gmail.com </h2>
<a class="btn btn-info" href="https://github.com/OskarBir/RubyOnRailsApp" role="button">GitHub</a>

app/views/pages/exam.html.erb
<h1 style="text-align:center;"><%= t('choose.language') %></h1>
<br/>
<div class="center">
  <%= link_to t('polish') + " --> " + t('english'), pages_algorithm_path(id: params[:id], lang: 1, alg: 1), class: 'btn btn-warning button_font', style: 'width:550px; height: 70px;' %>
  <br/>
  <br/>
  <%= link_to t('english') + " --> " + t('polish'), pages_algorithm_path(id: params[:id], lang: 0, alg: 1), class: 'btn btn-warning button_font', style: 'width:550px; height: 70px;' %>
</div>

app/views/pages/index.html.erb
<h1 style="text-align:center;"><%= t('choose.category') %></h1>
<div class="center">
  <% @categories.each do |category| %>
    <br/>
    <%= link_to "#{category.name}", pages_subcategory_list_path(id: category.id), class: 'btn btn-warning button_font', style: 'width:550px; height: 70px;' %>
    <br/>
  <% end %>
</div>

app/views/pages/my_result.html.erb
<p id="notice"><%= notice %></p>

<h1 style="text-align:center;"><%= t('my_results') %></h1>

<table class="table table-hover">
  <thead>
  <tr>
    <th><%= t('admin.result') + " [%]" %></th>
    <th><%= t('admin.word') %></th>
    <th><%= t('admin.result_date') %></th>
  </tr>
  </thead>

  <tbody>
  <% @results.each do |result| %>
    <tr>
      <td><%= result.result %></td>
      <td><%= Word.find(result.word_id).name %></td>
      <td><%= result.created_at %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/pages/score.html.erb
<h1 style="text-align:center;"><%= t('score') + " #{@score.to_s}" + " %" %></h1>
<br/>
<div class="center">
  <br/>
  <%= link_to t('return_to_category'), root_path, class: 'btn btn-warning button_font', style: 'width:550px; height: 70px;' %>
  <br/>
  <br/>
  <% if current_user %>
    <%= link_to t('my_results'), pages_my_result_path, class: 'btn btn-warning button_font', style: 'width:550px; height: 70px;' %>
    <br/>
  <% end %>
</div>

app/views/pages/subcategory_list.html.erb
<h1 style="text-align:center;"><%= t('choose.subcategory') %></h1>
<div class="center">
  <% @subcategories.each do |subcategory| %>
    <br/>
    <%= link_to "#{subcategory.name}", pages_word_list_path(id: subcategory.id), class: 'btn btn-warning button_font', style: 'width:550px; height: 70px;' %>
    <br/>
  <% end %>
</div>

app/views/pages/test.html.erb
<h1 style="text-align:center;"><%= t('choose.language') %></h1>
<div class="center">
  <br/>
  <%= link_to t('polish') + " --> " + t('english'), pages_algorithm_path(id: params[:id], lang: 1, alg: 0), class: 'btn btn-warning button_font', style: 'width:550px; height: 70px;' %>
  <br/>
  <br/>
  <%= link_to t('english') + " --> " + t('polish'), pages_algorithm_path(id: params[:id], lang: 0, alg: 0), class: 'btn btn-warning button_font', style: 'width:550px; height: 70px;' %>
  <br/>
</div>

app/views/pages/word.html.erb
<% @words.each do |set| %>
  <div class="center">
    <h1 style="text-align:center;"><%= t('choose.word') + set.name %></h1>
    <h2><%= t('word_list') %></h2>
    <table class="table table-hover">
      <thead>
      <tr>
        <th><%= t('polish') %></th>
        <th><%= t('english') %></th>
      <tr>
      </thead>

      <tbody>
      <% i = 0 %>
      <% while i < @words_hash.keys.length do %>
        <tr>
          <td><%= @words_hash.keys[0 + i] %></td>
          <td><%= @words_hash.values[0 + i] %></td>
        <tr>
          <% i += 1 %>
      <% end %>
      </tbody>
    </table>
    <br/>
    <h3><%= t('word_info') %></h3>

    <%= link_to "Test", pages_test_path(id: set.id), class: 'btn btn-warning button_font', style: 'width:550px; height: 70px;' %>
    <br/>
    <br/>
    <% if current_user %>
      <%= link_to t('exam'), pages_exam_path(id: set.id), class: 'btn btn-warning button_font', style: 'width:550px; height: 70px;' %>
    <% end %>
  </div>
<% end %>

app/views/pages/word_list.html.erb
<h1 style="text-align:center;"><%= t('choose.set') %></h1>

<div class="center">
  <% @words.each do |word| %>
    <br/>
    <%= link_to "#{word.name}", pages_word_path(id: word.id), class: 'btn btn-warning button_font', style: 'width:550px; height: 70px;' %>
    <br/>
  <% end %>
</div>