config/routes.rb
Rails.application.routes.draw do

  resources :words
  resources :results
  resources :subcategories
  resources :categories
  devise_for :users, :controllers => {registrations: 'registrations'}
  root to: 'pages#index'

  get 'pages/contact'

  get 'pages/about'

  get 'pages/subcategory_list'

  get 'pages/word_list'

  get 'pages/word'

  get 'pages/test'

  get 'pages/exam'

  get 'pages/algorithm'

  get 'pages/score'

  get 'pages/my_result'

  get 'set_language/polish'

  get 'set_language/english'

end

app/views/layouts/_navigationbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to t('app_name'), root_path, class: 'navbar-brand' %>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <% if current_user ? current_user.admin : current_user %>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#"><%= t('admin.panel') %>
            <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to t('admin.category'), categories_path %></li>
            <li><%= link_to t('admin.subcategory'), subcategories_path %></li>
            <li><%= link_to t('admin.word'), words_path %></li>
            <li><%= link_to t('admin.result'), results_path %></li>
          </ul>
        </li>
      <% end %>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if current_user %>
        <li><%= link_to t('my_results'), pages_my_result_path %></li>
        <li><%= link_to t('profile_edit'), edit_user_registration_path %></li>
        <li><%= link_to t('log_out'), destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to t('sign_up'), new_user_registration_path %></li>
        <li><%= link_to t('sign_in'), new_user_session_path %></li>
      <% end %>
    </ul>
    <ul class="nav navbar-nav">
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#"><%= t('choose.language') %>
          <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><%= link_to t('english'), set_language_english_path %></li>
          <li><%= link_to t('polish'), set_language_polish_path %></li>
        </ul>
      <li><%= link_to t('contact'), pages_contact_path %></li>
      <li><%= link_to t('about'), pages_about_path %></li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t('app_name') %></title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navigationbar' %>
<%= bootstrap_flash %>
<div class="container">
  <%= yield %>
</div>
</body>
</html>